In [1]:
import sys, os, inspect
sys.path.append("/home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL")

In [3]:
from tv.util.neucmd.hive_query_neusql import HiveNeuSQL
import time, logging
numeric_level = getattr(logging, 'DEBUG', None)
stdout_handler = logging.StreamHandler(sys.stdout)
logging.basicConfig(level=numeric_level,
                        format='%(asctime)s %(levelname)s %(name)s: %(message)s',
                        handlers=[stdout_handler])

In [3]:
#config = '/home/vbhargava/.tv_etl/dnow_nightly_platform.xml'

In [4]:
os.getenv("HOME")

'/home/vbhargava'

In [5]:
#!cat /home/vbhargava/.tv_etl/dnow_nightly_platform.xml

In [6]:
df = HiveNeuSQL.hive_query(raw=True, return_data=False, debug=True)

2021-02-04 06:45:52,548 DEBUG root: ** Query:
set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
show databases;
2021-02-04 06:45:52,549 DEBUG root: Hive query staging loc:tmp_hive_query_7621_139932945581888.hiveql
2021-02-04 06:45:52,550 DEBUG tv.util.neucmd.hive_query_neusql: ** Call: source /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/tv/util/neucmd/bash_scripts/Neu_cmd.sh && NeuSQL -f tmp_hive_query_7621_139932945581888.hiveql
COMMAND ID: 438650240 has Started!!
2021-02-04 06:45:55,709 INFO  P38 PID:11605 hivecli.py:141 - __init__ - Default hive version is set as 2.3
2021-02-04 06:45:56,430 INFO  P38 PID:11605 hivecli.py:1337 - getQHSHostName - Hive Tier Appname: production-sa-59.3
2021-02-04 06:45:56,476 INFO  P38 PID:11605 hivecli.py:1341 - getQHSHostName - Using Hive tier.
285512242.mdhist 100% ||||||||||||||||||||||||||||||| Time: 00:00:00   0.00 B/s
285512242.query 100% |||||||||||||||||||||||||||||||| Time: 00:00:00   0.00 B/s
which: no hbase in (/usr/local/rvm/gems/ruby-2.5.5/bin:/usr/local/rvm/gems/ruby-2.5.5@global/bin:/usr/local/rvm/rubies/ruby-2.5.5/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/lib/hustler/bin:/usr/lib/hustler3/bin:/usr/local/rvm/bin)
Switching Java Home to /usr/lib/jvm/java-1.8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=200m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/qubole/packages/hive1_2-59.0.16/2.3/hive1.2/lib/log4j-slf4j-impl-2.11.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/qubole/packages/tez-59.0.10/0.8.4/tez/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/qubole/packages/hadoop2-59.0.10/2.6.0/hadoop2/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

Logging initialized using configuration in file:/usr/lib/qubole/packages/hive1_2-59.0.16/2.3/hive1.2/conf/hive-log4j2.properties Async: false
Running Hive 2.3.6 version
Processing file s3://qubole-nightly/warehouse/NonManagedZone/qubole/scripts/bootstrap
Processing file s3://qubole-nightly/warehouse/NonManagedZone/qubole/scripts/hive/9176/77925/bootstrap
Processing file /media/ephemeral0/jobs/285512242/285512242.mdhist
[MapJoinCounter PostHook] COMMON_JOIN: 0 HINTED_MAPJOIN: 0 HINTED_MAPJOIN_LOCAL: 0 CONVERTED_MAPJOIN: 0 CONVERTED_MAPJOIN_LOCAL: 0 BACKUP_COMMON_JOIN: 0 BUCKET_MAP_JOIN: 0 HYBRID_HASH_JOIN: 0 DYNAMIC_PARTITION_HASH_JOIN: 0 TOTAL_JOINS: 0
OK
Time taken: 7.357 seconds, Fetched: 2983 row(s)
/media/ephemeral0/jobs/285512242/285512242.md 100% || Time: 00:00:00   0.00 B/s

JOB ID: 438650240
STATUS: done
2021-02-04 06:47:56,176 INFO tv.util.neucmd.hive_query_neusql: Exit_Code :0

In [7]:
!xmlstarlet sel -T -t -v "/configroot/qubole_settings/set[name='URL']/stringval" /home/vbhargava/.tv_etl/dnow_nightly_platform.xml

failed to load external entity "/home/vbhargava/.tv_etl/dnow_nightly_platform.xml"

In [7]:
df

''

In [8]:
df = HiveNeuSQL.hive_query(return_data=True, debug=True)

2021-02-04 06:51:58,182 DEBUG root: ** Query:
set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
show databases;
2021-02-04 06:51:58,183 DEBUG tv.util.neucmd.hive_query_neusql: ** Call: source /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/tv/util/neucmd/bash_scripts/Neu_cmd.sh && NeuSQL -S -e "set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
show databases;"

In [9]:
df

                                         database_name
0                                                 1234
1    aaaaaaaaaaabbbbbbbbbbbcccccccccccdddddddddddee...
2                                     adp_client2_core
3                                     adp_client2_lbis
4                             adp_client2_qa_vbhargava
5                                      adp_client2_raw
6                                      adp_client2_src
7                                     adp_client3_core
8                                     adp_client3_lbis
9                             adp_client3_qa_vbhargava
10                                     adp_client3_raw
11                                     adp_client3_src
12                                    adp_client4_core
13                                    adp_client4_lbis
14                                  adp_client4_presrc
15                            adp_client4_qa_vbhargava
16                                     adp_client4_raw
17                                     adp_client4_src
18                                 adp_client4_staging
19                                adp_test_client_core
20                                adp_test_client_lbis
21                              adp_test_client_presrc
22                       adp_test_client_qa_mspnightly
23                                 adp_test_client_raw
24                                 adp_test_client_src
25                             adp_test_client_staging
26                                       aiptest2_core
27                                       aiptest2_lbis
28                                     aiptest2_presrc
29                                       aiptest2_prod
..                                                 ...
970                    mz_marketshare9_dev_client_core
971                              mz_mra_qa_client_core
972               mz_mra_qa_client_regression_mra_core
973                        mz_mtamodel_fix_client_core
974                                 mz_mvp_28_jan_core
975                             mz_mvp_test_28_01_core
976                            mz_mvp_test_28_jan_core
977                            mz_mvp_test_29_jan_core
978                            mz_mvp_test_client_core
979                                   mz_mvp_test_core
980                           mz_mvp_test_feature_core
981                          mz_mvp_testing_28_01_core
982                mz_new_qa_test_client_creation_core
983                     mz_new_qa_test_client_wed_core
984                              mz_nightly_dev10_core
985                        mz_nightly_dev10_temp1_core
986                         mz_nightly_dev10_temp_core
987                     mz_nightly_dev_mmm_client_core
988                     mz_nightly_dev_mta_client_core
989              mz_nightly_dev_mtadefault_client_core
990                         mz_nightly_dev_ua_dev_core
991                       mz_nightly_dn_phase_dev_core
992                                mz_nightly_txn_core
993                     mz_nightly_una_dev_client_core
994                            mz_nightly_una_uat_core
995                        mz_nightlyclients_test_core
996                                   mz_qa8_11_0_core
997                            mz_qa8_client_11_0_core
998                                 mz_qa_13638_3_core
999                                   mz_qa_13638_core

[1000 rows x 1 columns]

In [11]:
import re
st = 'dnow_nightly_platform_config.xml'
regx = '^.*[Pp]latform_config.xml$'
mat = re.match(regx, st)

In [12]:
mat[0]

'dnow_nightly_platform_config.xml'

In [13]:
import  glob
search_path = '/home/vbhargava/.tv_etl/*platform_config.xml'
glob.glob(search_path)

['/home/vbhargava/.tv_etl/dnow_nightly_platform_config.xml']

## SPARK Test

In [13]:
from tv.util.neucmd.spark_query_neusql import SparkNeuSQL

User Home Dir: /home/vbhargava
2021-02-03 06:38:57,342 DEBUG tv.configs: User Home Dir: /home/vbhargava
2021-02-03 06:38:57,343 DEBUG tv.configs: config_loc: /home/vbhargava/.tv_etl/config.properties
2021-02-03 06:38:57,345 WARNING tv.configs:
 Config:- Configuration picked from section:[DEV_test8] of
        config: /home/vbhargava/.tv_etl/config.properties

In [6]:
df3 = SparkNeuSQL.spark_query(return_data=True, debug=True)

2021-02-02 09:32:58,619 INFO root: spark_config_loc: /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/conf/spark_settings.conf
2021-02-02 09:32:58,620 DEBUG root: ** Query:
show databases;
2021-02-02 09:32:58,621 DEBUG tv.util.neucmd.spark_query_neusql: ** Call: source /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/tv/util/neucmd/bash_scripts/Neu_cmd.sh && NeuSQL -S -engine=spark -e "show databases;" -sc /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/conf/spark_settings.conf
Spark is enabled on the cluster

In [7]:
df3

                                                  1234
0    aaaaaaaaaaabbbbbbbbbbbcccccccccccdddddddddddee...
1                                     adp_client2_core
2                                     adp_client2_lbis
3                             adp_client2_qa_vbhargava
4                                      adp_client2_raw
5                                      adp_client2_src
6                                     adp_client3_core
7                                     adp_client3_lbis
8                             adp_client3_qa_vbhargava
9                                      adp_client3_raw
10                                     adp_client3_src
11                                    adp_client4_core
12                                    adp_client4_lbis
13                                  adp_client4_presrc
14                            adp_client4_qa_vbhargava
15                                     adp_client4_raw
16                                     adp_client4_src
17                                 adp_client4_staging
18                                adp_test_client_core
19                                adp_test_client_lbis
20                              adp_test_client_presrc
21                       adp_test_client_qa_mspnightly
22                                 adp_test_client_raw
23                                 adp_test_client_src
24                             adp_test_client_staging
25                                       aiptest2_core
26                                       aiptest2_lbis
27                                     aiptest2_presrc
28                                       aiptest2_prod
29                              aiptest2_qa_mspnightly
..                                                 ...
970                              mz_mra_qa_client_core
971               mz_mra_qa_client_regression_mra_core
972                        mz_mtamodel_fix_client_core
973                                 mz_mvp_28_jan_core
974                             mz_mvp_test_28_01_core
975                            mz_mvp_test_28_jan_core
976                            mz_mvp_test_29_jan_core
977                            mz_mvp_test_client_core
978                                   mz_mvp_test_core
979                           mz_mvp_test_feature_core
980                          mz_mvp_testing_28_01_core
981                mz_new_qa_test_client_creation_core
982                     mz_new_qa_test_client_wed_core
983                              mz_nightly_dev10_core
984                        mz_nightly_dev10_temp1_core
985                         mz_nightly_dev10_temp_core
986                     mz_nightly_dev_mmm_client_core
987                     mz_nightly_dev_mta_client_core
988              mz_nightly_dev_mtadefault_client_core
989                         mz_nightly_dev_ua_dev_core
990                       mz_nightly_dn_phase_dev_core
991                                mz_nightly_txn_core
992                     mz_nightly_una_dev_client_core
993                            mz_nightly_una_uat_core
994                        mz_nightlyclients_test_core
995                                   mz_qa8_11_0_core
996                            mz_qa8_client_11_0_core
997                                 mz_qa_13638_3_core
998                                   mz_qa_13638_core
999                                     mz_qa_809_core

[1000 rows x 1 columns]

In [8]:
df4 = SparkNeuSQL.spark_query(return_data=False, debug=True)

2021-02-02 10:00:12,847 INFO root: spark_config_loc: /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/conf/spark_settings.conf
2021-02-02 10:00:12,848 DEBUG root: ** Query:
show databases;
2021-02-02 10:00:12,849 DEBUG root: Spark query staging loc:tmp_spark_query_101847_139851730507584.sql
2021-02-02 10:00:12,851 DEBUG tv.util.neucmd.spark_query_neusql: ** Call: source /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/tv/util/neucmd/bash_scripts/Neu_cmd.sh && NeuSQL -v -engine=spark -f tmp_spark_query_101847_139851730507584.sql -sc /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/conf/spark_settings.conf
Spark is enabled on the cluster
2021-02-02 10:03:19,423 INFO tv.util.neucmd.spark_query_neusql: Exit_Code :0

### NEU SQL

In [10]:
from tv.util.neucmd.neusql import SQL
from tv.configs import Config
#Config.intialise()

User Home Dir: /home/vbhargava
2021-02-04 07:24:59,191 DEBUG tv.configs: User Home Dir: /home/vbhargava
2021-02-04 07:24:59,193 DEBUG tv.configs: config_loc: /home/vbhargava/.tv_etl/config.properties
2021-02-04 07:24:59,195 WARNING tv.configs:
 Config:- Configuration picked from section:[DEV_test8] of
        config: /home/vbhargava/.tv_etl/config.properties

In [14]:
df5 = SQL.run_query(return_data=True, debug=True, execution_engine='HIVE')

2021-02-04 07:28:56,772 DEBUG root: ** Query:
set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
show databases;
2021-02-04 07:28:56,774 DEBUG tv.util.neucmd.hive_query_neusql: ** Call: source /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/tv/util/neucmd/bash_scripts/Neu_cmd.sh && NeuSQL -S -e "set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
show databases;"

In [15]:
df5

                                         database_name
0                                                 1234
1    aaaaaaaaaaabbbbbbbbbbbcccccccccccdddddddddddee...
2                                     adp_client2_core
3                                     adp_client2_lbis
4                             adp_client2_qa_vbhargava
5                                      adp_client2_raw
6                                      adp_client2_src
7                                     adp_client3_core
8                                     adp_client3_lbis
9                             adp_client3_qa_vbhargava
10                                     adp_client3_raw
11                                     adp_client3_src
12                                    adp_client4_core
13                                    adp_client4_lbis
14                                  adp_client4_presrc
15                            adp_client4_qa_vbhargava
16                                     adp_client4_raw
17                                     adp_client4_src
18                                 adp_client4_staging
19                                adp_test_client_core
20                                adp_test_client_lbis
21                              adp_test_client_presrc
22                       adp_test_client_qa_mspnightly
23                                 adp_test_client_raw
24                                 adp_test_client_src
25                             adp_test_client_staging
26                                       aiptest2_core
27                                       aiptest2_lbis
28                                     aiptest2_presrc
29                                       aiptest2_prod
..                                                 ...
970                    mz_marketshare9_dev_client_core
971                              mz_mra_qa_client_core
972               mz_mra_qa_client_regression_mra_core
973                        mz_mtamodel_fix_client_core
974                                 mz_mvp_28_jan_core
975                             mz_mvp_test_28_01_core
976                            mz_mvp_test_28_jan_core
977                            mz_mvp_test_29_jan_core
978                            mz_mvp_test_client_core
979                                   mz_mvp_test_core
980                           mz_mvp_test_feature_core
981                          mz_mvp_testing_28_01_core
982                mz_new_qa_test_client_creation_core
983                     mz_new_qa_test_client_wed_core
984                              mz_nightly_dev10_core
985                        mz_nightly_dev10_temp1_core
986                         mz_nightly_dev10_temp_core
987                     mz_nightly_dev_mmm_client_core
988                     mz_nightly_dev_mta_client_core
989              mz_nightly_dev_mtadefault_client_core
990                         mz_nightly_dev_ua_dev_core
991                       mz_nightly_dn_phase_dev_core
992                                mz_nightly_txn_core
993                     mz_nightly_una_dev_client_core
994                            mz_nightly_una_uat_core
995                        mz_nightlyclients_test_core
996                                   mz_qa8_11_0_core
997                            mz_qa8_client_11_0_core
998                                 mz_qa_13638_3_core
999                                   mz_qa_13638_core

[1000 rows x 1 columns]

In [7]:
df6 = SQL.run_query(query='SHOW PARTITIONS tv_mta_staging_dev_test8.ext_raw_kantar_log' ,execution_engine= 'Hive', return_data=True, debug=True)

2021-02-03 10:02:26,663 DEBUG root: ** Query:
set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
SHOW PARTITIONS tv_mta_staging_dev_test8.ext_raw_kantar_log;
2021-02-03 10:02:26,664 DEBUG tv.util.neucmd.hive_query_neusql: ** Call: source /home/vbhargava/fb_v9.0_merged/msaction_backend/common/BU3.0_core/util/Py_utils/ETL/tv/util/neucmd/bash_scripts/Neu_cmd.sh && NeuSQL -S -e "set hive.cli.print.header=true; set hive.resultset.use.unique.column.names=false;
SHOW PARTITIONS tv_mta_staging_dev_test8.ext_raw_kantar_log;"

In [11]:
df5.loc[0:]

       year=2019/week=0/file_name=tv_locnet
0      year=2019/week=0/file_name=tv_locsln
1     year=2019/week=0/file_name=tv_locspot
2      year=2019/week=0/file_name=tv_locsyn
3      year=2019/week=0/file_name=tv_natcab
4      year=2019/week=0/file_name=tv_natcue
5      year=2019/week=0/file_name=tv_natnet
6      year=2019/week=0/file_name=tv_natsln
7      year=2019/week=0/file_name=tv_natsyn
8      year=2019/week=1/file_name=tv_locnet
9      year=2019/week=1/file_name=tv_locsln
10    year=2019/week=1/file_name=tv_locspot
11     year=2019/week=1/file_name=tv_locsyn
12     year=2019/week=1/file_name=tv_natcab
13     year=2019/week=1/file_name=tv_natcue
14     year=2019/week=1/file_name=tv_natnet
15     year=2019/week=1/file_name=tv_natsln
16     year=2019/week=1/file_name=tv_natsyn
17    year=2019/week=10/file_name=tv_locnet
18    year=2019/week=10/file_name=tv_locsln
19   year=2019/week=10/file_name=tv_locspot
20    year=2019/week=10/file_name=tv_locsyn
21    year=2019/week=10/file_name=tv_natcab
22    year=2019/week=10/file_name=tv_natcue
23    year=2019/week=10/file_name=tv_natnet
24    year=2019/week=10/file_name=tv_natsln
25    year=2019/week=10/file_name=tv_natsyn
26    year=2019/week=11/file_name=tv_locnet
27    year=2019/week=11/file_name=tv_locsln
28   year=2019/week=11/file_name=tv_locspot
29    year=2019/week=11/file_name=tv_locsyn
..                                      ...
590    year=2020/week=6/file_name=tv_natnet
591    year=2020/week=6/file_name=tv_natsln
592    year=2020/week=6/file_name=tv_natsyn
593    year=2020/week=7/file_name=tv_locnet
594    year=2020/week=7/file_name=tv_locsln
595   year=2020/week=7/file_name=tv_locspot
596    year=2020/week=7/file_name=tv_locsyn
597    year=2020/week=7/file_name=tv_natcab
598    year=2020/week=7/file_name=tv_natcue
599    year=2020/week=7/file_name=tv_natnet
600    year=2020/week=7/file_name=tv_natsln
601    year=2020/week=7/file_name=tv_natsyn
602    year=2020/week=8/file_name=tv_locnet
603    year=2020/week=8/file_name=tv_locsln
604   year=2020/week=8/file_name=tv_locspot
605    year=2020/week=8/file_name=tv_locsyn
606    year=2020/week=8/file_name=tv_natcab
607    year=2020/week=8/file_name=tv_natcue
608    year=2020/week=8/file_name=tv_natnet
609    year=2020/week=8/file_name=tv_natsln
610    year=2020/week=8/file_name=tv_natsyn
611    year=2020/week=9/file_name=tv_locnet
612    year=2020/week=9/file_name=tv_locsln
613   year=2020/week=9/file_name=tv_locspot
614    year=2020/week=9/file_name=tv_locsyn
615    year=2020/week=9/file_name=tv_natcab
616    year=2020/week=9/file_name=tv_natcue
617    year=2020/week=9/file_name=tv_natnet
618    year=2020/week=9/file_name=tv_natsln
619    year=2020/week=9/file_name=tv_natsyn

[620 rows x 1 columns]

In [12]:
df6

                                  partition
0      year=2019/week=0/file_name=tv_locnet
1      year=2019/week=0/file_name=tv_locsln
2     year=2019/week=0/file_name=tv_locspot
3      year=2019/week=0/file_name=tv_locsyn
4      year=2019/week=0/file_name=tv_natcab
5      year=2019/week=0/file_name=tv_natcue
6      year=2019/week=0/file_name=tv_natnet
7      year=2019/week=0/file_name=tv_natsln
8      year=2019/week=0/file_name=tv_natsyn
9      year=2019/week=1/file_name=tv_locnet
10     year=2019/week=1/file_name=tv_locsln
11    year=2019/week=1/file_name=tv_locspot
12     year=2019/week=1/file_name=tv_locsyn
13     year=2019/week=1/file_name=tv_natcab
14     year=2019/week=1/file_name=tv_natcue
15     year=2019/week=1/file_name=tv_natnet
16     year=2019/week=1/file_name=tv_natsln
17     year=2019/week=1/file_name=tv_natsyn
18    year=2019/week=10/file_name=tv_locnet
19    year=2019/week=10/file_name=tv_locsln
20   year=2019/week=10/file_name=tv_locspot
21    year=2019/week=10/file_name=tv_locsyn
22    year=2019/week=10/file_name=tv_natcab
23    year=2019/week=10/file_name=tv_natcue
24    year=2019/week=10/file_name=tv_natnet
25    year=2019/week=10/file_name=tv_natsln
26    year=2019/week=10/file_name=tv_natsyn
27    year=2019/week=11/file_name=tv_locnet
28    year=2019/week=11/file_name=tv_locsln
29   year=2019/week=11/file_name=tv_locspot
..                                      ...
591    year=2020/week=6/file_name=tv_natnet
592    year=2020/week=6/file_name=tv_natsln
593    year=2020/week=6/file_name=tv_natsyn
594    year=2020/week=7/file_name=tv_locnet
595    year=2020/week=7/file_name=tv_locsln
596   year=2020/week=7/file_name=tv_locspot
597    year=2020/week=7/file_name=tv_locsyn
598    year=2020/week=7/file_name=tv_natcab
599    year=2020/week=7/file_name=tv_natcue
600    year=2020/week=7/file_name=tv_natnet
601    year=2020/week=7/file_name=tv_natsln
602    year=2020/week=7/file_name=tv_natsyn
603    year=2020/week=8/file_name=tv_locnet
604    year=2020/week=8/file_name=tv_locsln
605   year=2020/week=8/file_name=tv_locspot
606    year=2020/week=8/file_name=tv_locsyn
607    year=2020/week=8/file_name=tv_natcab
608    year=2020/week=8/file_name=tv_natcue
609    year=2020/week=8/file_name=tv_natnet
610    year=2020/week=8/file_name=tv_natsln
611    year=2020/week=8/file_name=tv_natsyn
612    year=2020/week=9/file_name=tv_locnet
613    year=2020/week=9/file_name=tv_locsln
614   year=2020/week=9/file_name=tv_locspot
615    year=2020/week=9/file_name=tv_locsyn
616    year=2020/week=9/file_name=tv_natcab
617    year=2020/week=9/file_name=tv_natcue
618    year=2020/week=9/file_name=tv_natnet
619    year=2020/week=9/file_name=tv_natsln
620    year=2020/week=9/file_name=tv_natsyn

[621 rows x 1 columns]